Proforma/Areas/Admin/Controllers/ProformaProgramsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Proforma.DAL;

namespace Proforma.Areas.Admin.Controllers
{
    public class ProformaProgramsController : Controller
    {
        private SourcingGuideDevEntities db = new SourcingGuideDevEntities();

        // GET: Admin/ProformaPrograms
        public ActionResult Index(int companyId, int? id = 0)
        {
            ProformaProgram proformaProgram = db.ProformaPrograms.Find(id);
            ViewBag.CompanyId = companyId;
            ViewBag.proformaPrograms = db.ProformaPrograms.Where(a => a.CompanyId == companyId).ToList();
            return View(proformaProgram);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "ProformaProgramId,CompanyId,Name,Description,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] ProformaProgram proformaProgram)
        {
            ViewBag.CompanyId = proformaProgram.CompanyId;
            ViewBag.proformaPrograms = db.ProformaPrograms.Where(a => a.CompanyId == proformaProgram.CompanyId).ToList();

            if (ModelState.IsValid)
            {
                if (proformaProgram.ProformaProgramId == 0)
                {
                    proformaProgram.CreatedDate = DateTime.Now;
                    proformaProgram.ModifiedDate = DateTime.Now;
                    db.ProformaPrograms.Add(proformaProgram);
                }
                else
                {
                    var record = db.ProformaPrograms.FirstOrDefault(a => a.ProformaProgramId == proformaProgram.ProformaProgramId);
                    record.Name = proformaProgram.Name;
                    record.CompanyId = proformaProgram.CompanyId;
                    record.ModifiedDate = DateTime.Now;
                    db.Entry(record).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index", new { companyId = proformaProgram.CompanyId });
            }

            return View(proformaProgram);
        }

        // GET: Admin/ProformaPrograms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProformaProgram proformaProgram = db.ProformaPrograms.Find(id);
            if (proformaProgram == null)
            {
                return HttpNotFound();
            }
            return View(proformaProgram);
        }

        // GET: Admin/ProformaPrograms/Create
        public ActionResult Create()
        {
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType");
            return View();
        }

        // POST: Admin/ProformaPrograms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProformaProgramId,CompanyId,Name,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] ProformaProgram proformaProgram)
        {
            if (ModelState.IsValid)
            {
                db.ProformaPrograms.Add(proformaProgram);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType", proformaProgram.CompanyId);
            return View(proformaProgram);
        }

        // GET: Admin/ProformaPrograms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProformaProgram proformaProgram = db.ProformaPrograms.Find(id);
            if (proformaProgram == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType", proformaProgram.CompanyId);
            return View(proformaProgram);
        }

        // POST: Admin/ProformaPrograms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProformaProgramId,CompanyId,Name,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] ProformaProgram proformaProgram)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proformaProgram).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType", proformaProgram.CompanyId);
            return View(proformaProgram);
        }

        // GET: Admin/ProformaPrograms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProformaProgram proformaProgram = db.ProformaPrograms.Find(id);
            if (proformaProgram == null)
            {
                return HttpNotFound();
            }
            return View(proformaProgram);
        }

        // POST: Admin/ProformaPrograms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProformaProgram proformaProgram = db.ProformaPrograms.Find(id);
            db.ProformaPrograms.Remove(proformaProgram);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proforma/Areas/Admin/Views/ProformaPrograms/Create.cshtml
@model Proforma.Models.ProformaProgram

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProformaProgram</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proforma/Areas/Admin/Views/ProformaPrograms/Delete.cshtml
@model Proforma.Models.ProformaProgram

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProformaProgram</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.PartnerType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.PartnerType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proforma/Areas/Admin/Views/ProformaPrograms/Details.cshtml
@model Proforma.Models.ProformaProgram

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProformaProgram</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.PartnerType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.PartnerType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProformaProgramId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Proforma/Areas/Admin/Views/ProformaPrograms/Edit.cshtml
@model Proforma.Models.ProformaProgram

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProformaProgram</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProformaProgramId)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proforma/Areas/Admin/Views/ProformaPrograms/Index.cshtml
@model Proforma.DAL.ProformaProgram

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("Index", "ProformaPrograms", FormMethod.Post, new { @id = "frmProformaPrograms" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProformaProgram</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (Request.QueryString["id"] != null)
        {
            @Html.HiddenFor(model => model.ProformaProgramId)
        }
        @Html.HiddenFor(model => model.CompanyId, new { @value = ViewBag.CompanyId })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @if (null != ViewBag.proformaPrograms)
    {
        foreach (var item in ViewBag.proformaPrograms)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    <a href="~/Admin/ProformaPrograms/Index?companyId=@item.CompanyId&id=@item.ProformaProgramId">Edit</a> |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProformaProgramId })
                </td>
            </tr>
        }
    }

</table>


<script>

  // When the browser is ready...
    $(document).ready(function () {

    // Setup form validation on the #register-form element
        $("#frmProformaPrograms").validate({

        // Specify the validation rules
        rules: {
            Description: "required",
            Name: {
                required: true,
                maxlength: 2000
            }
        },

        // Specify the validation error messages
        messages: {

        },

        submitHandler: function(form) {
            form.submit();
        }
    });

  });

</script>