Proforma/Areas/Admin/Controllers/ProductsCapabilitiesController.cs
using Proforma.DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Proforma.Areas.Admin.Controllers
{
    public class ProductsCapabilitiesController : Controller
    {
        private SourcingGuideDevEntities db = new SourcingGuideDevEntities();

        // GET: Admin/ProductsCapabilities
        public ActionResult Index(int companyId, int? id = 0)
        {
            ProductsCapability productsCapability = db.ProductsCapabilities.Find(id);
            ViewBag.productsCapabilities = db.ProductsCapabilities.Where(a => a.CompanyId == companyId).ToList();
            ViewBag.CompanyId = companyId;
            return View(productsCapability);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "ProductsCapabilityId,CompanyId,Name,Description,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] ProductsCapability productsCapability)
        {

            ViewBag.productsCapabilities = db.ProductsCapabilities.Where(a => a.CompanyId == productsCapability.CompanyId).ToList();
            ViewBag.CompanyId = productsCapability.CompanyId;
            if (ModelState.IsValid)
            {
                if (productsCapability.ProductsCapabilityId == 0)
                {
                    productsCapability.CreatedDate = DateTime.Now;
                    productsCapability.ModifiedDate = DateTime.Now;
                    db.ProductsCapabilities.Add(productsCapability);
                }
                else
                {
                    var record = db.ProductsCapabilities.FirstOrDefault(a => a.ProductsCapabilityId == productsCapability.ProductsCapabilityId);
                    record.Name = productsCapability.Name;
                    record.CompanyId = productsCapability.CompanyId;
                    record.ModifiedDate = DateTime.Now;
                    db.Entry(record).State = EntityState.Modified;
                }

                db.SaveChanges();
                return RedirectToAction("Index", new { companyId = productsCapability.CompanyId });
            }

            return View(productsCapability);
        }

        // GET: Admin/ProductsCapabilities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsCapability productsCapability = db.ProductsCapabilities.Find(id);
            if (productsCapability == null)
            {
                return HttpNotFound();
            }
            return View(productsCapability);
        }

        // GET: Admin/ProductsCapabilities/Create
        public ActionResult Create()
        {
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType");
            return View();
        }

        // POST: Admin/ProductsCapabilities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductsCapabilityId,CompanyId,Name,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] ProductsCapability productsCapability)
        {
            if (ModelState.IsValid)
            {
                db.ProductsCapabilities.Add(productsCapability);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType", productsCapability.CompanyId);
            return View(productsCapability);
        }

        // GET: Admin/ProductsCapabilities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsCapability productsCapability = db.ProductsCapabilities.Find(id);
            if (productsCapability == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType", productsCapability.CompanyId);
            return View(productsCapability);
        }

        // POST: Admin/ProductsCapabilities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductsCapabilityId,CompanyId,Name,CreatedBy,CreatedDate,ModifiedBy,ModifiedDate")] ProductsCapability productsCapability)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productsCapability).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "PartnerType", productsCapability.CompanyId);
            return View(productsCapability);
        }

        // GET: Admin/ProductsCapabilities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductsCapability productsCapability = db.ProductsCapabilities.Find(id);
            if (productsCapability == null)
            {
                return HttpNotFound();
            }
            return View(productsCapability);
        }

        // POST: Admin/ProductsCapabilities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            ProductsCapability productsCapability = db.ProductsCapabilities.Find(id);
            int companyid = productsCapability.CompanyId;
            db.ProductsCapabilities.Remove(productsCapability);
            db.SaveChanges();
            return RedirectToAction("Index", new { companyId = companyid });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Proforma/Areas/Admin/Views/ProductsCapabilities/Create.cshtml
@model Proforma.Models.ProductsCapability

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductsCapability</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proforma/Areas/Admin/Views/ProductsCapabilities/Delete.cshtml
@model Proforma.Models.ProductsCapability

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductsCapability</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.PartnerType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.PartnerType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Proforma/Areas/Admin/Views/ProductsCapabilities/Details.cshtml
@model Proforma.Models.ProductsCapability

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProductsCapability</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.PartnerType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.PartnerType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductsCapabilityId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Proforma/Areas/Admin/Views/ProductsCapabilities/Edit.cshtml
@model Proforma.Models.ProductsCapability

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductsCapability</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductsCapabilityId)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Proforma/Areas/Admin/Views/ProductsCapabilities/Index.cshtml
@model Proforma.DAL.ProductsCapability

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "ProductsCapabilities", FormMethod.Post, new { @id = "frmProductsCapabilities" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductsCapability</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (Request.QueryString["id"] != null)
        {
            @Html.HiddenFor(model => model.ProductsCapabilityId)
        }
        @Html.HiddenFor(model => model.CompanyId, new { @value = ViewBag.CompanyId })
        @*<div class="form-group">
                @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control",@id="dllCompany" })
                    @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @maxlength = "500", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (null != ViewBag.productsCapabilities)
        {
            foreach (var item in ViewBag.productsCapabilities)
            {
                <tr>
                    <td>
                        @item.Name

                    </td>
                    <td>
                        <a href="~/Admin/ProductsCapabilities/Index?companyId=@item.CompanyId&id=@item.ProductsCapabilityId">Edit</a> |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ProductsCapabilityId })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>


<script>

  // When the browser is ready...
    $(document).ready(function () {

    // Setup form validation on the #register-form element
      $("#frmProductsCapabilities").validate({

        // Specify the validation rules
        rules: {
            Name: {
                required: true,
                maxlength: 2000
            }
        },

        // Specify the validation error messages
        messages: {

        },

        submitHandler: function(form) {
            form.submit();
        }
    });

  });

</script>