Proforma/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string PartnerType { get; set; }
        public string CompanyName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string FTPSite { get; set; }
        public string ArtEmail { get; set; }
        public string OrderEmail { get; set; }
        public string FOBPointInCanada { get; set; }
        public string QuoteinCanadianDollars { get; set; }
        public string PrimaryContactName { get; set; }
        public string PrimaryContactEmail { get; set; }
        public string PrimaryContactExtension { get; set; }
        public string PrimaryContactDirectLine { get; set; }
        public string SecondaryContactName { get; set; }
        public string SecondaryContactEmail { get; set; }
        public string SecondaryContactExtension { get; set; }
        public string SecondaryContactDirectLine { get; set; }
        public string TradeOnly { get; set; }
        public string Union { get; set; }
        public string ASI { get; set; }
        public string PPAI { get; set; }
        public string PPPC { get; set; }
        public string SAGE { get; set; }
        public string UPIC { get; set; }
        public string Certifications { get; set; }
        public string MinorityOwned { get; set; }
        public string ProformaPricing { get; set; }
        public string ProformaPrograms { get; set; }
        public string ProductsNCapabilities { get; set; }
        public string Rushor24hour { get; set; }
    
        public virtual Category Category { get; set; }
    }
}

Proforma/Areas/Admin/Controllers/CompaniesController.cs
using Proforma.DAL;
using Proforma.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Proforma.Areas.Admin.Controllers
{
    [Authorize(Roles = "SuperAdmin, CompanyAdmin")]
    public class CompaniesController : Controller
    {
        SourcingGuideDevEntities _db = new SourcingGuideDevEntities();
        // GET: Admin/Companies
        public ActionResult Index()
        {
            var companies = _db.Companies.ToList();
            List<CompaniesModel> lstCompanies = new List<CompaniesModel>();
            if (companies.Count() > 0)
            {
                foreach (var company in companies)
                {
                    CompaniesModel model = new CompaniesModel();
                    model.CompanyId = company.CompanyId;
                    model.PartnerType = company.PartnerType;
                    model.CompanyName = company.CompanyName;
                    model.ASI = company.ASI;
                    model.PPAI = company.PPAI;
                    model.PPPC = company.PPPC;
                    model.SAGE = company.SAGE;
                    model.UPIC = company.UPIC;
                    lstCompanies.Add(model);
                }

            }
            return View(lstCompanies);
        }

        public ActionResult Company(int companyId)
        {
            CompanyModel model = new CompanyModel();
            var company = _db.Companies.FirstOrDefault(a => a.CompanyId == companyId);
            if (null != company)
            {
                ContactInfoModel _ContactInfo = GetContactInfo(company);
                model.ContactInfo = _ContactInfo;

                ProductsCapabilityModel _ProductsCapabilityModel = GetProductCapabilities(company.CompanyId);
                model.ProductsCapability = _ProductsCapabilityModel;

                ProformaProgramModel _ProformaProgramModel = GetProFormaPrograms(company.CompanyId);
                model.ProformaProgram = _ProformaProgramModel;
            }


            return View(model);
        }

        [HttpPost]
        public ActionResult ProformaProgramsPartial(ProformaProgramModel model)
        {
            var record = new ProformaProgram();
            if (model.ProformaProgramId > 0)
            {
                record = _db.ProformaPrograms.FirstOrDefault(a => a.ProformaProgramId == model.ProformaProgramId);
            }

            record.Name = model.Name;
            record.CompanyId = model.CompanyId;


            if (model.ProformaProgramId == 0)
            {
                record.CreatedDate = DateTime.Now;
                _db.ProformaPrograms.Add(record);
            }
            else
            {
                record.ModifiedDate = DateTime.Now;
                _db.Entry(record).State = EntityState.Modified;
            }
            _db.SaveChanges();

            ProformaProgramModel _ProformaProgramModel = GetProFormaPrograms(model.CompanyId);
            return PartialView(_ProformaProgramModel);
        }

        [HttpPost]
        public ActionResult ProductCapabilitiesPartial(ProductsCapabilityModel model)
        {
            var record = new ProductsCapability();
            if (model.ProductsCapabilityId > 0)
            {
                record = _db.ProductsCapabilities.FirstOrDefault(a => a.ProductsCapabilityId == model.ProductsCapabilityId);
            }

            record.Name = model.Name;
            record.CompanyId = model.CompanyId;


            if (model.ProductsCapabilityId == 0)
            {
                record.CreatedDate = DateTime.Now;
                _db.ProductsCapabilities.Add(record);
            }
            else
            {
                record.ModifiedDate = DateTime.Now;
                _db.Entry(record).State = EntityState.Modified;
            }
            _db.SaveChanges();

            ProductsCapabilityModel _ProductsCapabilityModel = GetProductCapabilities(model.CompanyId);

            return PartialView(_ProductsCapabilityModel);
        }

        [HttpPost]
        public ActionResult ContactInfoPartial(ContactInfoModel model)
        {
            var company = _db.Companies.FirstOrDefault(a => a.CompanyId == model.CompanyId);
            ContactInfoModel _ContactInfo = new ContactInfoModel();
            if (null != company)
            {
                company.CompanyName = model.CompanyName;
                company.CompanyId = model.CompanyId;
                company.ASI = model.ASI;
                company.PPAI = model.PPAI;
                company.SAGE = model.SAGE;
                company.StreetAddress = model.StreetAddress;
                company.City = model.City;
                company.State = model.State;
                company.ZipCode = model.ZipCode;
                company.Website = model.Website;
                company.FOBPointInCanada = model.FOBPointInCanada;
                company.PrimaryContactFirstName = model.PrimaryContactFirstName + " " + model.PrimaryContactLastName;
                company.PrimaryContactEmail = model.PrimaryContactEmail;
                company.PrimaryContactDirectLine = model.PrimaryContactDirectLine;
                company.PrimaryContactFax = model.PrimaryContactFax;
                company.PrimaryContactTradeOnly = model.PrimaryContactTradeOnly;
                company.SecondaryContactFirstName = model.SecondaryContactFirstName + " " + model.SecondaryContactLastName;
                company.SecondaryContactEmail = model.SecondaryContactEmail;
                company.SecondaryContactDirectLine = model.SecondaryContactDirectLine;
                company.SecondaryContactFax = model.SecondaryContactFax;
                company.SecondaryContactTradeOnly = model.SecondaryContactTradeOnly;
                //  company.SecondaryContactAffilations = "";
                //company.PrimaryContactAffilations = "";
                _db.Entry(company).State = EntityState.Modified;
                _db.SaveChanges();

                //To Do: Edit company data
                _ContactInfo = GetContactInfo(company);
            }
            return PartialView(_ContactInfo);
        }

        public ContactInfoModel GetContactInfo(Company company)
        {
            ContactInfoModel _ContactInfo = new ContactInfoModel();
            _ContactInfo.CompanyName = company.CompanyName;
            _ContactInfo.CompanyId = company.CompanyId;
            _ContactInfo.ASI = company.ASI;
            _ContactInfo.PPAI = company.PPAI;
            _ContactInfo.SAGE = company.SAGE;
            _ContactInfo.StreetAddress = company.StreetAddress;
            _ContactInfo.City = company.City;
            _ContactInfo.State = company.State;
            _ContactInfo.ZipCode = company.ZipCode;
            _ContactInfo.Website = company.Website;
            _ContactInfo.FOBPointInCanada = company.FOBPointInCanada;
            _ContactInfo.PrimaryContactFirstName = company.PrimaryContactFirstName;
            _ContactInfo.PrimaryContactLastName = company.PrimaryContactLastName;
            _ContactInfo.PrimaryContactEmail = company.PrimaryContactEmail;
            _ContactInfo.PrimaryContactDirectLine = company.PrimaryContactDirectLine;
            _ContactInfo.PrimaryContactAffilations = company.PrimaryContactAffiliations;
            _ContactInfo.PrimaryContactFax = company.PrimaryContactFax;
            _ContactInfo.PrimaryContactTradeOnly = company.PrimaryContactTradeOnly;
            _ContactInfo.SecondaryContactFirstName = company.SecondaryContactFirstName;
            _ContactInfo.SecondaryContactLastName = company.SecondaryContactLastName;
            _ContactInfo.SecondaryContactEmail = company.SecondaryContactEmail;
            _ContactInfo.SecondaryContactDirectLine = company.SecondaryContactDirectLine;
            _ContactInfo.SecondaryContactAffilations = company.SecondaryContactAffiliations;
            _ContactInfo.SecondaryContactFax = company.SecondaryContactFax;
            _ContactInfo.SecondaryContactTradeOnly = company.SecondaryContactTradeOnly;
            _ContactInfo.TertiaryContactFirstName = company.TertiaryContactFirstName;
            _ContactInfo.TertiaryContactLastName = company.TertiaryContactLastName;
            _ContactInfo.TertiaryContactEmail = company.TertiaryContactEmail;
            _ContactInfo.TertiaryContactDirectLine = company.TertiaryContactDirectLine;
            _ContactInfo.TertiaryContactAffilations = company.TertiaryContactAffiliations;
            _ContactInfo.TertiaryContactFax = company.TertiaryContactFax;
            _ContactInfo.TertiaryContactTradeOnly = company.TertiaryContactTradeOnly;
            _ContactInfo.CompanyLogo = company.Company_Logo;
            return _ContactInfo;
        }

        public ProformaProgramModel GetProFormaPrograms(int companyId)
        {
            ProformaProgramModel _ProformaProgramModel = new ProformaProgramModel();
            _ProformaProgramModel.CompanyId = companyId;
            var _ProformaPrograms = _db.ProformaPrograms.Where(a => a.CompanyId == companyId).ToList();
            if (_ProformaPrograms.Count > 0)
            {
                List<ProformaProgram> lstProductsCapability = new List<ProformaProgram>();
                foreach (var item in _ProformaPrograms)
                {
                    ProformaProgram _ProformaProgram = new ProformaProgram();
                    _ProformaProgram.CompanyId = item.CompanyId;
                    _ProformaProgram.Name = item.Name;
                    _ProformaProgram.ProformaProgramId = item.ProformaProgramId;
                    lstProductsCapability.Add(_ProformaProgram);
                }
                _ProformaProgramModel.lstProformaProgram = lstProductsCapability;
            }
            return _ProformaProgramModel;
        }

Proforma/Areas/Admin/Views/Companies/Index.cshtml
@model  List<Proforma.Areas.Admin.ViewModels.CompaniesModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
            <th>CompanyName</th>
            <th>PartnerType</th>
            <th>ASI</th>
            <th>PPAI</th>
            <th>PPPC</th>
            <th>SAGE</th>
            <th>UPIC</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PartnerType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ASI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PPAI)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PPPC)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SAGE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UPIC)
                </td>
                <td style="width: 25%;">
                    <a href="~/Admin/Companies/Company?companyId=@item.CompanyId">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Proforma/Areas/Admin/Views/Companies/ProductCapabilitiesPartial.cshtml
@model Proforma.Areas.Admin.ViewModels.ProductsCapabilityModel
@*@using (Html.BeginForm("ProductsCapabilities", "Companies", FormMethod.Post, new { area = "Admin", @id = "frmProductsCapabilities" }))
    {*@
<div role="tabpanel" class="tab-pane" id="ProductCapabilities">
    <div class="general-info-wrap prd-cap-wrap padding-btn-0">
        <form id="frmProductsCapabilities">
            <ul class="general-info-from-wrap padding-btn-40 clearfix">
                <li>
                    <div class="field-group">
                        <label class="field-label">Product Capability Name</label>
                        @Html.HiddenFor(model => model.CompanyId)
                        <input type="hidden" id="ProductCapabilityId" value="0"/>
                        @Html.TextAreaFor(model => model.Name, new { @id = "ProductCapabilityName" })
                        @*<input type="button" id="btnProductCapability" class="add-btn" value="Save" />*@
                        <a id="btnProductCapability" class="add-btn">Save</a>
                    </div>
                </li>
            </ul>
        </form>
    </div>
    <div class="prd-cap-list-wrap events-list-wrap">
        <ul id="lstProductCapabilities">
            <li >
                <ul class="prd-cap-list-hdr">

                    <li style="border-right:none;">Description</li>
                </ul>
            </li>
            @if (Model.lstProductsCapabilities.Count() > 0)
            {
                foreach (var item in Model.lstProductsCapabilities)
                {
                    var EditId = "editCapability" + item.ProductsCapabilityId;
                    var DeleteId = "deleteCapability" + item.ProductsCapabilityId;
                    var DescId = "capabilityDetails" + item.ProductsCapabilityId;
                    var prodId = "ProductCapability" + item.ProductsCapabilityId;
                    <li id="@prodId">
                        <ul class="prd-cap-list-dtl">
                            <li id="@DescId">@item.Name</li>
                            @*<li id="@DeleteId"><a href="~/Admin/ProductsCapabilities/Delete?id=@item.ProductsCapabilityId"><img src="~/Content/images/delete-icon.png" alt="Delete"></a></li>
                                <li id="@EditId"><a href="~/Admin/ProductsCapabilities/Index?companyId=@item.CompanyId&id=@item.ProductsCapabilityId"><img src="~/Content/images/edit-icon.png" alt="Edit"></a></li>*@
                            <li><a id="@DeleteId" onclick="fnDeleteProductCapability(this)" class="crud-icons"><img src="~/Content/images/delete-icon.png" alt="Delete"></a></li>
                            <li><a id="@EditId" onclick="fnEditProductCapability(this)" class="crud-icons"><img src="~/Content/images/edit-icon.png" alt="Edit"></a></li>
                        </ul>
                    </li>
                }
            }
        </ul>
    </div>
</div>
@*}*@

Proforma/Areas/Admin/Views/Companies/ProformaProgramsPartial.cshtml
@model Proforma.Areas.Admin.ViewModels.ProformaProgramModel

<div role="tabpanel" class="tab-pane" id="ProformaProgramsSpecials">
    <div class="general-info-wrap prd-cap-wrap padding-btn-0">
        <form id="frmProformaPrograms">
            <ul class="general-info-from-wrap padding-btn-40 clearfix">
                <li>
                        @Html.HiddenFor(model => model.CompanyId)
                        <div class="field-group">
                            <label class="field-label">Proforma Program</label>
                            <input type="hidden" id="ProformaProgramId" value="0" />
                            @Html.TextAreaFor(model => model.Name, new { @id= "ProformaProgramName" })
                            @*<input type="button" id="btnProformaPrograms" class="add-btn" value="Add" />*@
                            <a id="btnProformaPrograms" class="add-btn">Save</a>
                        </div>
                </li>
            </ul>
        </form>
    </div>
    <div class="prd-cap-list-wrap events-list-wrap">
        <ul id="lstProformaPrograms">
            <li>
                <ul class="prd-cap-list-hdr">
                    <li style="border-right:none;">Description</li>
                </ul>
            </li>
            @if (Model.lstProformaProgram.Count() > 0)
            {
                foreach (var item in Model.lstProformaProgram)
                {
                    var EditId = "editProgram" + item.ProformaProgramId;
                    var DeleteId = "deleteProgram" + item.ProformaProgramId;
                    var DescId = "ProgramDetails" + item.ProformaProgramId;
                    var prodId = "ProformaProgram" + item.ProformaProgramId;
                    <li id="@prodId">
                        <ul class="prd-cap-list-dtl">
                            <li id="@DescId">@item.Name</li>
                            <li><a id="@DeleteId" onclick="fnDeleteProformaProgram(this)" class="crud-icons"><img src="~/Content/images/delete-icon.png" alt="Delete"></a></li>
                            <li><a id="@EditId" onclick="fnEditProformaProgram(this)" class="crud-icons"><img src="~/Content/images/edit-icon.png" alt="Edit"></a></li>
                        </ul>
                    </li>
                }
            }
        </ul>
    </div>
</div>